=== RecipeMD/RecipeMD/testcases/testcase.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "RecipeMD Test Case",
    "type": "object",
    "required": [
        "title",
        "description",
        "tags",
        "yields",
        "ingredients",
        "ingredient_groups",
        "instructions"
    ],
    "properties": {
        "title": {
            "type": "string"
        },
        "description": {
            "type": [
                "string",
                "null"
            ]
        },
        "yields": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/amount"
            }
        },
        "tags": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "ingredients": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/ingredient"
            }
        },
        "ingredient_groups": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/ingredient_group"
            }
        },
        "instructions": {
            "type": [
                "string",
                "null"
            ]
        }
    },
    "definitions": {
        "ingredient": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "amount": {
                    "anyOf": [
                        {
                            "$ref": "#/definitions/amount"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "link": {
                    "type": [
                        "string",
                        "null"
                    ]
                }
            }
        },
        "ingredient_group": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "title": {
                    "type": "string"
                },
                "ingredients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ingredient"
                    }
                },
                "ingredient_groups": {
                    "type": "array",
                    "items": [
                        {
                            "$ref": "#/definitions/ingredient_group"
                        }
                    ]
                }
            }
        },
        "amount": {
            "type": [
                "object"
            ],
            "properties": {
                "factor": {
                    "type": "string"
                },
                "unit": {
                    "type": [
                        "string",
                        "null"
                    ]
                }
            }
        }
    }
}

=== RecipeMD/RecipeMD/testcases/recipe.json
{
  "title": "Title",
  "description": "The description describes this recipe. It is delicious!\n\nIt can have multiple lines an may even include pictures.\n\n<img src=\"../logo/recipemd-mark.svg\" />",
  "yields": [
    {
      "factor": "5",
      "unit": "cups"
    },
    {
      "factor": "20",
      "unit": "ml"
    },
    {
      "factor": "5.5",
      "unit": "Tassen"
    }
  ],
  "tags": [
    "vegetarian",
    "vegan",
    "not a real recipe"
  ],
  "ingredients": [
    {
      "name": "ungrouped ingredient",
      "amount": {
        "factor": "5",
        "unit": null
      },
      "link": null
    },
    {
      "name": "grouped ingredient",
      "amount": {
        "factor": "5.2",
        "unit": "ml"
      },
      "link": null
    }
  ],
  "ingredient_groups": [
    {
      "title": "Group 1",
      "ingredients": [
        {
          "name": "link ingredient",
          "amount": {
            "factor": "1",
            "unit": null
          },
          "link": "./ingredients.md"
        },
        {
          "name": "unit is optional",
          "amount": null,
          "link": null
        }
      ],
      "ingredient_groups": [
        {
          "title": "Subgroup 1.1",
          "ingredients": [
            {
              "name": "ingredient",
              "amount": {
                "factor": "1.25",
                "unit": "ml"
              },
              "link": null
            }
          ],
          "ingredient_groups": []
        }
      ]
    },
    {
      "title": "Group 2",
      "ingredients": [
        {
          "name": "text isn't optional",
          "amount": null,
          "link": null
        },
        {
          "name": "amount is valid without factor",
          "amount": {
            "factor": null,
            "unit": "hey"
          },
          "link": null
        }
      ],
      "ingredient_groups": []
    }
  ],
  "instructions": "Instructions are very instructive."
}
