=== RecipeMD/RecipeMD/testcases/testcase.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "RecipeMD Test Case",
    "type": "object",
    "required": [
        "title",
        "description",
        "tags",
        "yields",
        "ingredients",
        "ingredient_groups",
        "instructions"
    ],
    "properties": {
        "title": {
            "type": "string"
        },
        "description": {
            "type": [
                "string",
                "null"
            ]
        },
        "yields": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/amount"
            }
        },
        "tags": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "ingredients": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/ingredient"
            }
        },
        "ingredient_groups": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/ingredient_group"
            }
        },
        "instructions": {
            "type": [
                "string",
                "null"
            ]
        }
    },
    "definitions": {
        "ingredient": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "amount": {
                    "anyOf": [
                        {
                            "$ref": "#/definitions/amount"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "link": {
                    "type": [
                        "string",
                        "null"
                    ]
                }
            }
        },
        "ingredient_group": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "title": {
                    "type": "string"
                },
                "ingredients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ingredient"
                    }
                },
                "ingredient_groups": {
                    "type": "array",
                    "items": [
                        {
                            "$ref": "#/definitions/ingredient_group"
                        }
                    ]
                }
            }
        },
        "amount": {
            "type": [
                "object"
            ],
            "properties": {
                "factor": {
                    "type": "string"
                },
                "unit": {
                    "type": [
                        "string",
                        "null"
                    ]
                }
            }
        }
    }
}

=== RecipeMD/RecipeMD/testcases/cases/ingredients_groups.json
{
  "title": "Recipe with ingredient groups",
  "description": null,
  "yields": [],
  "tags": [],
  "ingredients": [
    {
      "name": "ingredient 0",
      "amount": null,
      "link": null
    }
  ],
  "ingredient_groups": [
    {
      "title": "Group 1",
      "ingredients": [
        {
          "name": "ingredient 1",
          "amount": null,
          "link": null
        },
        {
          "name": "ingredient 2",
          "amount": null,
          "link": null
        }
      ],
      "ingredient_groups": [
        {
          "title": "Subgroup 1.1",
          "ingredients": [
            {
              "name": "ingredient 3",
              "amount": null,
              "link": null
            },
            {
              "name": "ingredient 4",
              "amount": null,
              "link": null
            }
          ],
          "ingredient_groups": [
            {
              "title": "Subgroup 1.1.1 (Two level deeper headline, still one lever deeper group)",
              "ingredients": [
                {
                  "name": "ingredient 5",
                  "amount": null,
                  "link": null
                }
              ],
              "ingredient_groups": []
            },
            {
              "title": "Subgroup 1.1.2 (One level deeper headline)",
              "ingredients": [
                {
                  "name": "ingredient 6",
                  "amount": null,
                  "link": null
                }
              ],
              "ingredient_groups": []
            }
          ]
        }
      ]
    },
    {
      "title": "Group 2",
      "ingredients": [
        {
          "name": "ingredient 7",
          "amount": null,
          "link": null
        },
        {
          "name": "ingredient 8",
          "amount": null,
          "link": null
        }
      ],
      "ingredient_groups": []
    }
  ],
  "instructions": null
}

=== RecipeMD/RecipeMD/testcases/cases/ingredients_groups_multiple_lists.json
{
  "ingredients": [
    {
      "name": "ingredient 0",
      "amount": null,
      "link": null
    }
  ],
  "ingredient_groups": [
    {
      "ingredients": [
        {
          "name": "ingredient 1",
          "amount": null,
          "link": null
        },
        {
          "name": "ingredient 2",
          "amount": null,
          "link": null
        },
        {
          "name": "ingredient 3 (2nd list, ingredients go into same group)",
          "amount": null,
          "link": null
        },
        {
          "name": "ingredient 4",
          "amount": null,
          "link": null
        },
        {
          "name": "ingredient 5 (3nd list, ingredients go into same group)",
          "amount": null,
          "link": null
        },
        {
          "name": "ingredient 6",
          "amount": null,
          "link": null
        }
      ],
      "ingredient_groups": [],
      "title": "Group 1"
    }
  ],
  "title": "Recipe with ingredient groups with multiple lists",
  "description": null,
  "yields": [],
  "tags": [],
  "instructions": null
}

=== RecipeMD/RecipeMD/testcases/ingredients_multiline.json
{
  "title": "Multiline Ingredients",
  "description": null,
  "yields": [],
  "tags": [],
  "ingredients": [
    {
      "name": "This is a long ingredient\n\n  it spans multiple paragraphs\n  \n  this may be unusual but is valid",
      "amount": null,
      "link": null
    },
    {
      "name": "this is a normal boring ingredient",
      "amount": null,
      "link": null
    },
    {
      "name": "is an amount that\n\n  is the amount of *this* ingredient",
      "amount": {
        "factor": "5",
        "unit": "ml"
      },
      "link": null
    },
    {
      "name": "is an amount that stands alone on the first line",
      "amount": {
        "factor": "5",
        "unit": "grams"
      },
      "link": null
    },
    {
      "name": "[this is a link](some other recipe)",
      "amount": null,
      "link": null
    },
    {
      "name": "[this is not a link](some other recipe)\n\n  since links must wrap the whole ingredient text",
      "amount": null,
      "link": null
    }
  ],
  "ingredient_groups": [],
  "instructions": null
}

=== RecipeMD/RecipeMD/testcases/ingredients_sublist.json
{
  "title": "Recipe with ingredients",
  "description": null,
  "yields": [],
  "tags": [],
  "ingredients": [
    {
      "name": "water",
      "amount": {
        "factor": "20",
        "unit": "ml"
      },
      "link": null
    },
    {
      "name": "earl grey, hot\n  - nested sublist\n  - these items are not new ingredients, but part of the contents \n    of the top-level ingredient\n    - same goes for deeper nesting",
      "amount": {
        "factor": "1",
        "unit": "cup"
      },
      "link": null
    },
    {
      "name": "coffee",
      "amount": {
        "factor": "1.5",
        "unit": "cup"
      },
      "link": null
    }
  ],
  "ingredient_groups": [],
  "instructions": null
}

=== RecipeMD/RecipeMD/testcases/commonmark_reference_links.json
{
  "title": "Title",
  "description": "[step_0]: https://example.org\n\nLinks: [Step 0][step_0]., [Step 1][step_1].\n\n[step_1]: https://example.org",
  "yields": [],
  "tags": [],
  "ingredients": [
    {
      "name": "Thing",
      "amount": {
        "factor": "1",
        "unit": null
      },
      "link": null
    }
  ],
  "ingredient_groups": [],
  "instructions": "[step_2]: https://example.org\n\nLinks: [Step 2][step_2]., [Step 3][step_3].\n\n[step_3]: https://example.org"
}

=== RecipeMD/RecipeMD/testcases/cases/ingredients_links.json
{
  "title": "Ingredients with Links",
  "description": null,
  "yields": [],
  "tags": [],
  "ingredients": [
    {
      "name": "link to something",
      "amount": null,
      "link": "./another_recipe.md"
    },
    {
      "name": "link to something else",
      "amount": null,
      "link": "http://example.org"
    },
    {
      "name": "link to something with amount",
      "amount": {
        "factor": "5",
        "unit": "ml"
      },
      "link": "http://example.org"
    },
    {
      "name": "link with spaces in target",
      "amount": null,
      "link": "./foo%20bar.md"
    },
    {
      "name": "link with title that is ignored",
      "amount": null,
      "link": "./foo.md"
    },
    {
      "name": "[not parsed as a link](http://example.org) due to additional text after it",
      "amount": null,
      "link": null
    },
    {
      "name": "[not parsed as a link](http://example.org)\n  \n  due to second paragraph",
      "amount": null,
      "link": null
    }
  ],
  "ingredient_groups": [],
  "instructions": null
}

=== RecipeMD/RecipeMD/testcases/ingredients_links.json
{
  "title": "Ingredients with Links",
  "description": null,
  "yields": [],
  "tags": [],
  "ingredients": [
    {
      "name": "link to something",
      "amount": null,
      "link": "./another_recipe.md"
    },
    {
      "name": "link to something else",
      "amount": null,
      "link": "http://example.org"
    },
    {
      "name": "link to something with amount",
      "amount": {
        "factor": "5",
        "unit": "ml"
      },
      "link": "http://example.org"
    }
  ],
  "ingredient_groups": [],
  "instructions": null
}

=== RecipeMD/RecipeMD/testcases/ingredients.json
{
  "title": "Recipe with ingredients",
  "description": null,
  "yields": [],
  "tags": [],
  "ingredients": [
    {
      "name": "water",
      "amount": {
        "factor": "20",
        "unit": "ml"
      },
      "link": null
    },
    {
      "name": "earl grey, hot",
      "amount": {
        "factor": "1",
        "unit": "cup"
      },
      "link": null
    },
    {
      "name": "coffee",
      "amount": {
        "factor": "1.5",
        "unit": "cup"
      },
      "link": null
    },
    {
      "name": "cheese",
      "amount": {
        "factor": "0.25",
        "unit": "kg"
      },
      "link": null
    },
    {
      "name": "salt",
      "amount": null,
      "link": null
    },
    {
      "name": "ingredients may contain *markdown*",
      "amount": null,
      "link": null
    }
  ],
  "ingredient_groups": [],
  "instructions": null
}
